### ISSUE TITLE
Binder throws errors when using `copier` - directory does not exist

### ISSUE THREAD

**Issue by 392781** [UCSB-PSTAT/devcontainer-template#3]
Running copier without an existing `starter-code` directory throws the following error:
![image](https://github.com/UCSB-PSTAT/devcontainer-template/assets/25296775/38b024dc-5cc7-416c-b55b-1d6137d52da7)

**Solution:** `starter-code` should already exist or should be included via `mkdir starter-code`

**Comment by syoh** [comment]
Something must be different in our systems. For me, I can run `copier copy gh:UCSB-PSTAT/devcontainer-template starter-code` and it will create `starter-code` directory for me

![image](https://github.com/UCSB-PSTAT/devcontainer-template/assets/1441512/a749f0c7-458b-4527-8e81-f36eb87ea0aa)

Could you try again?

**Comment by 392781** [comment]
I tried again and it required me to make `starter-code` to build.

**Comment by syoh** [comment]
Interesting. I wonder what the difference is

**Comment by syoh** [comment]
I started a branch (`docker-compose`) for a rewrite and binder has been removed: https://github.com/UCSB-PSTAT/devcontainer-template/tree/docker-compose

Try using Codespace with the `docker-compose` branch. Readme has been updated, too
